# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["LC_ALL"] = "en_US.UTF-8"

$provisionScript = <<-EOF
    export LC_ALL=en_US.UTF-8
    sudo apt-get -y update
EOF

Vagrant.configure("2") do |config|
  config.vm.define "ubuntu-test" do |item|
    item.vm.box = "ubuntu/bionic64"
    item.vm.box_check_update = false
    item.vm.hostname = "ubuntu-test.host"
    
    item.vm.network "public_network", bridge: "enp30s0"
    item.vm.network "private_network", ip: "192.168.0.10"
    item.vm.network "forwarded_port", guest: 80, host: 5000, host_ip: "127.0.0.1"

    item.vm.synced_folder "shared_folder", "/vagrant_data"
    item.vm.synced_folder ".", "/vagrant", disabled: true

    item.vm.provider "virtualbox" do |vb|
      vb.name = "ubuntu-test.vm"
      # vb.memory = 1024
      vb.check_guest_additions = false
    end

    item.vm.provision "shell", inline: $provisionScript
  end



end
