# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["LC_ALL"] = "en_US.UTF-8"

$provisionScriptServer = <<-EOF
    export LC_ALL=en_US.UTF-8
    sudo apt-get -y update
    #sudo apt-get -y install software-properties-common
    sudo apt-get -y install ansible
EOF

$provisionScriptNode = <<-EOF
    # export LC_ALL=en_US.UTF-8
    sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
    sudo systemctl restart sshd
EOF

Vagrant.configure("2") do |config|

  config.vm.define "ansible-roles-server" do |item|
    item.vm.box = "ubuntu/bionic64"
    item.vm.box_check_update = false
    item.vm.hostname = "ansible-roles-server.host"
    item.vm.network "private_network", ip: "192.168.0.10"
    item.vm.provider "virtualbox" do |vb|
      vb.name = "ansible-roles-server.vm"
      vb.memory = 512
      vb.check_guest_additions = false
    end
    item.vm.provision "shell", inline: $provisionScriptServer
  end

  config.vm.define "ansible-roles-node" do |item|
    item.vm.box = "ubuntu/bionic64"
    item.vm.box_check_update = false
    item.vm.hostname = "ansible-roles-node.host"
    item.vm.network "private_network", ip: "192.168.0.11"
    item.vm.provider "virtualbox" do |vb|
      vb.name = "ansible-roles-node.vm"
      vb.memory = 512
      vb.check_guest_additions = false
    end
    item.vm.provision "shell", inline: $provisionScriptNode
  end

end
