version: '3'
services:
  zabbix-server:
    image: "zabbix/zabbix-server-mysql:ubuntu-4.2.6"
    #restart: always
    environment:
      DB_SERVER_HOST: "mysql-server-for-zabbix"
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ZBX_DEBUGLEVEL: 3
    depends_on:
      - "mysql-server-for-zabbix"
  mysql-server-for-zabbix:
    image: "mysql:5.7"
    command: --default-authentication-plugin=mysql_native_password
    #ports:
    #  - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
