- hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: "Add users"
      user:
        name: "{{ item.name }}"
        password: "{{ item.pass | password_hash('sha512') }}"
      with_items: "{{ users }}"

    - name: "Add authorized keys"
      authorized_key:
        user: "{{ item.name }}"
        key: "{{ lookup('file', 'keys/id_rsa_'+ item.name + '.pub') }}"
      with_items: "{{ users }}"
