version: '3'
services:

  jenkins:
    build: build-jenkins
    image: demitt/jenkins-deploy-java-app
    container_name: "jenkins-lts"
    ports:
      - "8081:8080"
      - "50000:50000"
    environment:
      - JENKINS_USER=$JENKINS_USER
      - JENKINS_PASS=$JENKINS_PASS

      - TOMCAT_MANAGER_SCRIPT_USER=$TOMCAT_MANAGER_SCRIPT_USER
      - TOMCAT_MANAGER_SCRIPT_PASS=$TOMCAT_MANAGER_SCRIPT_PASS
      - TOMCAT_MANAGER_SCRIPT_CREDS_ID=tomcat-deployer
      - TOMCAT_MANAGER_SCRIPT_CREDS_DESCRIPTION=Local tomcat script user (for deploy)

  tomcat:
    build:
      context: build-tomcat
      args:
        - TOMCAT_MANAGER_SCRIPT_USER=$TOMCAT_MANAGER_SCRIPT_USER
        - TOMCAT_MANAGER_SCRIPT_PASS=$TOMCAT_MANAGER_SCRIPT_PASS
        - TOMCAT_MANAGER_GUI_USER=$TOMCAT_MANAGER_GUI_USER
        - TOMCAT_MANAGER_GUI_PASS=$TOMCAT_MANAGER_GUI_PASS
    image: demitt/tomcat-deploy-java-app
    container_name: "tomcat-9.0.26"
    ports:
      - "8082:8080"
